-- =====================================================================
-- 01_raw_objects.sql
-- Run as LOADER (worksheet, or: snow sql -c olist_loader -f ...)
-- Raw tables keep every source column as VARCHAR. Typing happens in
-- dbt staging, so a bad value never blocks a load.
-- =====================================================================
USE ROLE LOADER;
USE WAREHOUSE LOADING_WH;
USE SCHEMA RAW.OLIST;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('')
  ENCODING = 'UTF8'
  COMPRESSION = AUTO
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE STAGE IF NOT EXISTS OLIST_STAGE
  FILE_FORMAT = CSV_FORMAT
  COMMENT = 'Landing zone for Olist CSVs';

-- Metadata columns on every table:
--   _SOURCE_FILE  file the row came from
--   _SOURCE_ROW   row number inside that file
--   _LOADED_AT    load timestamp

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID VARCHAR, CUSTOMER_UNIQUE_ID VARCHAR, CUSTOMER_ZIP_CODE_PREFIX VARCHAR,
  CUSTOMER_CITY VARCHAR, CUSTOMER_STATE VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE GEOLOCATION (
  GEOLOCATION_ZIP_CODE_PREFIX VARCHAR, GEOLOCATION_LAT VARCHAR, GEOLOCATION_LNG VARCHAR,
  GEOLOCATION_CITY VARCHAR, GEOLOCATION_STATE VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID VARCHAR, CUSTOMER_ID VARCHAR, ORDER_STATUS VARCHAR,
  ORDER_PURCHASE_TIMESTAMP VARCHAR, ORDER_APPROVED_AT VARCHAR,
  ORDER_DELIVERED_CARRIER_DATE VARCHAR, ORDER_DELIVERED_CUSTOMER_DATE VARCHAR,
  ORDER_ESTIMATED_DELIVERY_DATE VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
  ORDER_ID VARCHAR, ORDER_ITEM_ID VARCHAR, PRODUCT_ID VARCHAR, SELLER_ID VARCHAR,
  SHIPPING_LIMIT_DATE VARCHAR, PRICE VARCHAR, FREIGHT_VALUE VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE ORDER_PAYMENTS (
  ORDER_ID VARCHAR, PAYMENT_SEQUENTIAL VARCHAR, PAYMENT_TYPE VARCHAR,
  PAYMENT_INSTALLMENTS VARCHAR, PAYMENT_VALUE VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE ORDER_REVIEWS (
  REVIEW_ID VARCHAR, ORDER_ID VARCHAR, REVIEW_SCORE VARCHAR,
  REVIEW_COMMENT_TITLE VARCHAR, REVIEW_COMMENT_MESSAGE VARCHAR,
  REVIEW_CREATION_DATE VARCHAR, REVIEW_ANSWER_TIMESTAMP VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

-- Column names keep Olist's original spelling ("lenght");
-- dbt staging renames them.
CREATE OR REPLACE TABLE PRODUCTS (
  PRODUCT_ID VARCHAR, PRODUCT_CATEGORY_NAME VARCHAR,
  PRODUCT_NAME_LENGHT VARCHAR, PRODUCT_DESCRIPTION_LENGHT VARCHAR,
  PRODUCT_PHOTOS_QTY VARCHAR, PRODUCT_WEIGHT_G VARCHAR,
  PRODUCT_LENGTH_CM VARCHAR, PRODUCT_HEIGHT_CM VARCHAR, PRODUCT_WIDTH_CM VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE SELLERS (
  SELLER_ID VARCHAR, SELLER_ZIP_CODE_PREFIX VARCHAR, SELLER_CITY VARCHAR, SELLER_STATE VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE PRODUCT_CATEGORY_TRANSLATION (
  PRODUCT_CATEGORY_NAME VARCHAR, PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR,
  _SOURCE_FILE VARCHAR, _SOURCE_ROW NUMBER, _LOADED_AT TIMESTAMP_LTZ
);

SHOW TABLES IN SCHEMA RAW.OLIST;
