-- =====================================================================
-- 02_copy_into.sql
-- Run as LOADER after the CSVs are in @OLIST_STAGE.
-- TRUNCATE + FORCE makes re-runs deterministic.
-- PATTERN matches both .csv (Snowsight upload) and .csv.gz (CLI PUT).
-- =====================================================================
USE ROLE LOADER;
USE WAREHOUSE LOADING_WH;
USE SCHEMA RAW.OLIST;

LIST @OLIST_STAGE;

TRUNCATE TABLE CUSTOMERS;
COPY INTO CUSTOMERS FROM (
  SELECT $1,$2,$3,$4,$5, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_customers_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE GEOLOCATION;
COPY INTO GEOLOCATION FROM (
  SELECT $1,$2,$3,$4,$5, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_geolocation_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE ORDERS;
COPY INTO ORDERS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_orders_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE ORDER_ITEMS;
COPY INTO ORDER_ITEMS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_order_items_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE ORDER_PAYMENTS;
COPY INTO ORDER_PAYMENTS FROM (
  SELECT $1,$2,$3,$4,$5, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_order_payments_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

-- Review comments contain quoted line breaks; the enclosed-field
-- setting in CSV_FORMAT keeps them inside one record.
TRUNCATE TABLE ORDER_REVIEWS;
COPY INTO ORDER_REVIEWS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_order_reviews_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE PRODUCTS;
COPY INTO PRODUCTS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_products_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE SELLERS;
COPY INTO SELLERS FROM (
  SELECT $1,$2,$3,$4, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*olist_sellers_dataset[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;

TRUNCATE TABLE PRODUCT_CATEGORY_TRANSLATION;
COPY INTO PRODUCT_CATEGORY_TRANSLATION FROM (
  SELECT $1,$2, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
  FROM @OLIST_STAGE)
PATTERN = '.*product_category_name_translation[.]csv([.]gz)?'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT) FORCE = TRUE;
